[repository]
name = "Hyprfoci"
authors = ["Pohlrabi"]
output = "build/libhyprfoci.so"
commit_pins = [
	["3e35797b18d35baae82657bb0438af88156e273f", "7499bcb08d7881a89bb752abc4eeb173ba8da618"],
]
build = [
	"meson compile -C build"
]
